### ISSUE TITLE
Missing credits for Android-Iconify

### ISSUE THREAD

**Issue by mikepenz** [Pierry/SimpleToast#1]
@Pierry please add the info that it uses the awesome library [Android-Iconify](https://github.com/JoanZapata/android-iconify) from @JoanZapata

**Comment by Pierry** [comment]
You're right! Sorry! =/

**Comment by mikepenz** [comment]
@Pierry no problem :D just add it ;)

**Comment by Pierry** [comment]
Added! :D

**Comment by JoanZapata** [comment]
Thanks @mikepenz and @Pierry.
To be accurate, credits are transitive, so you should also add something about `FontAwesome` and its creator, Dave Gandy, which is used by `Iconify`.

**Comment by Pierry** [comment]
Ok @JoanZapata, added. thanks! :+1:
